# Generated by Django 4.1.7 on 2023-03-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0002_chatbotoutput'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatBotOutput',
        ),
        migrations.AddField(
            model_name='userinput',
            name='output',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AlterField(
            model_name='userinput',
            name='input',
            field=models.TextField(),
        ),
    ]
