# Generated by Django 4.1.7 on 2023-03-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0003_delete_chatbotoutput_userinput_output_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='output',
            field=models.TextField(),
        ),
    ]
